from __future__ import annotations

import re

from utils.text import normalize_text

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "ferreteria": [
        "clavo",
        "clavos",
        "martillo",
        "tornillo",
        "tornillos",
        "herramienta",
        "herramientas",
        "material",
        "materiales",
        "construccion",
        "construcción",
        "pintura",
        "pinturas",
        "ferreteria",
        "ferretería",
        "ferrex",
        "ferremas",
        "ace hardware",
        "taller",
        "repuesto",
        "repuestos",
        "cemento",
        "electricidad",
        "sanitario",
    ],
    "supermercados": [
        "supermercado",
        "supermercados",
        "super",
        "mercado",
        "viveres",
        "víveres",
        "biggie",
        "biggie express",
        "stock",
        "superseis",
        "super seis",
        "super 6",
        "arete",
        "real",
    ],
    "combustible": [
        "combustible",
        "combustibles",
        "nafta",
        "cargar",
        "estacion de servicio",
        "estación de servicio",
        "shell",
        "copetrol",
        "petropar",
        "petrobras",
        "enex",
        "95",
        "97",
    ],
    "gastronomia": [
        "gastronomia",
        "gastronomía",
        "restaurant",
        "restaurante",
        "restaurantes",
        "comida",
        "comer",
        "almuerzo",
        "almorzar",
        "cena",
        "cenar",
        "cafe",
        "café",
        "cafeteria",
        "cafetería",
        "bar",
    ],
    "retail": [
        "retail",
        "shopping",
        "shoppings",
        "tienda",
        "tiendas",
        "comercio",
        "comercial",
        "departamento",
        "departamental",
        "privilege",
    ],
    "indumentaria": [
        "ropa",
        "indumentaria",
        "moda",
        "vestimenta",
        "calzado",
        "zapato",
        "zapatos",
        "boutique",
        "koala",
        "della poletti",
    ],
    "tecnologia": [
        "electro",
        "tecnologia",
        "tecnología",
        "electronica",
        "electrónica",
        "tecnologico",
        "tecnológico",
        "celular",
        "smartphone",
        "notebook",
        "laptop",
        "tv",
        "smart tv",
        "opentech",
        "hp store",
        "tigo",
        "personal",
        "alemania cell",
        "samsung",
        "apple",
        "informatica",
        "informÃ¡tica",
        "compu",
        "computadora",
        "celulares",
    ],
    "hogar": [
        "hogar",
        "mueble",
        "muebles",
        "decoracion",
        "decoración",
        "luminaria",
        "luminotecnia",
        "electrodomestico",
        "electrodoméstico",
        "cocina",
        "colchon",
        "colchón",
        "colchones",
        "casa parana",
    ],
    "salud": [
        "farmacia",
        "farmacias",
        "farma",
        "salud",
        "optica",
        "óptica",
        "clinica",
        "clínica",
        "laboratorio",
        "biggie farma",
    ],
    "viajes": [
        "viaje",
        "viajes",
        "turismo",
        "hotel",
        "hoteles",
        "pasaje",
        "pasajes",
        "aereo",
        "aéreo",
        "travel",
        "dtp travel",
    ],
    "entretenimiento": [
        "entretenimiento",
        "cine",
        "teatro",
        "show",
        "concierto",
        "diversion",
        "diversión",
        "parque",
        "ocio",
        "espectaculo",
        "club",
        "nautico",
        "deportivo",
        "eventos",
        "mbatovi",
        "aventura",
        "espectáculo",
    ],
}

PRODUCT_TO_CATEGORY: dict[str, str] = {
    keyword: category
    for category, keywords in CATEGORY_KEYWORDS.items()
    for keyword in keywords
}

CATEGORY_TO_MERCHANTS: dict[str, list[str]] = {
    "ferreteria": ["Ferrex", "Ferreteria Don Juan", "Ferremas", "Talleres y Repuestos"],
    "hogar": ["Casa Parana", "Luminotecnia", "Ferrex"],
    "supermercados": ["Stock", "Superseis", "Real", "Arete", "Biggie"],
    "combustible": ["Shell", "Copetrol", "Petropar", "Petrobras", "Enex"],
    "gastronomia": ["Biggie", "Della Poletti"],
    "retail": ["Privilege"],
    "indumentaria": ["Koala", "Della Poletti"],
    "tecnologia": ["Opentech", "HP Store", "Alemania Cell", "Samsung", "Tigo", "Personal"],
    "salud": ["Biggie Farma"],
    "viajes": ["Dtp Travel Group"],
    "entretenimiento": ["Biggie", "Mbatovi", "Club Nautico San Bernardino"],
}

MERCHANT_ALIASES: dict[str, list[str]] = {
    "Ferreteria Don Juan": ["don juan", "ferreteria don juan", "ferreteria donjuan"],
    "Ferrex": ["ferrex"],
    "Ferremas": ["ferremas"],
    "Shell": ["shell"],
    "Biggie": ["biggie", "biggie express"],
    "Biggie Farma": ["biggie farma"],
    "Copetrol": ["copetrol", "copetrol sa"],
    "Petropar": ["petropar"],
    "Petrobras": ["petrobras"],
    "Enex": ["enex"],
    "Stock": ["stock"],
    "Superseis": ["super seis", "superseis", "super 6"],
    "Real": ["real"],
    "Arete": ["arete"],
    "Koala": ["koala"],
    "Della Poletti": ["della poletti", "dellapoletti", "black della poletti"],
    "Opentech": ["opentech"],
    "HP Store": ["hp store", "hp"],
    "Alemania Cell": ["alemania cell"],
    "Samsung": ["samsung"],
    "Tigo": ["tigo"],
    "Personal": ["personal"],
    "Talleres y Repuestos": ["talleres y repuestos", "taller", "repuestos"],
    "Mbatovi": ["mbatovi"],
    "Club Nautico San Bernardino": ["club nautico san bernardino", "club nautico"],
    "Privilege": ["privilege"],
    "Dtp Travel Group": ["dtp travel group", "dtp travel"],
}

IMPORTANT_CATEGORIES = [
    "supermercados",
    "combustible",
    "gastronomia",
    "retail",
    "indumentaria",
    "tecnologia",
    "hogar",
    "salud",
    "viajes",
    "entretenimiento",
    "ferreteria",
]


def infer_category_from_text(text: str | None) -> str | None:
    if not text:
        return None
    normalized = normalize_text(text)
    for term, category in sorted(PRODUCT_TO_CATEGORY.items(), key=lambda item: len(item[0]), reverse=True):
        if re.search(rf"(^|\b){re.escape(term)}(\b|$)", normalized):
            return category
    return None
